# Generated by Django 4.2.6 on 2023-10-11 11:53

from django.db import migrations
import streams.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('heading', streams.blocks.TitleAndTextBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
